### ISSUE TITLE
does it support windows?

### ISSUE THREAD

**Issue by sutongkui** [462cmu/CMU462#1]
In the CMakeLists, it seems that we can build it in windows, but i  have tried several times, i use cmake to generate solution and then compile against visual studio 2012(also against 2015), still failed(bug about standard header file, like <cmath>)! I wonder if it supports windows?
thanks!

**Comment by Bryce-Summers** [comment]
I'm not sure if we ever officially supported Windows. There may have been a windows version passed around back in the day, but the gitHub version probably does not.

**Comment by sutongkui** [comment]
thanks, and I wonder if you have the windows version, I found it was compiled successfully against windows  in the project https://github.com/woyaofacai/CMU462_PhotonMapping, but i don't find the project, just some .png.
